languaje: node_js
script:
  - echo "deploying"
install:
  - yarn global add firebase-tools vuepress
after_success:
  - yarn install
  - yarn build
  - firebase deploy --token $FIREBASE_TOKEN
  - yarn twit
  - echo $TRAVIS_COMMIT_MESSAGE
cache:
  directories:
    - node_modules
    - dist
